### ISSUE TITLE
Duplication of the CustomRelationshipField

### ISSUE THREAD

**Issue by cherlow** [dcasia/custom-relationship-field#16]
Using CustomRelationshipField twice results in duplication of  the  first CustomRelationshipField e.g
` CustomRelationshipField::make('Child Prefixes', 'children', self::class),
 CustomRelationshipField::make('Parent Prefixes', 'parents', self::class),`

results in displaying the Child Prefixes Twice.

**Comment by cherlow** [comment]
Anyone?

**Comment by milewski** [comment]
Fixed here: https://github.com/dcasia/custom-relationship-field/pull/19
