### ISSUE TITLE
How do we use this with other models?

### ISSUE THREAD

**Issue by RyanPaiva56** [dcasia/custom-relationship-field#2]
How would we use this with a relation other than the same model? Like for your example this only displays other clients on the client page. I'm trying to display another model that belongs to the resource being looked at that isn't related by eloquent. Thank you very much for this package!

**Comment by RyanPaiva56** [comment]
I figured it out but would probably be helpful to others to update the docs a little.

use CustomRelationshipFieldTrait; and all of the customRelationX functions needs to go on the resource class being displayed, not the one being displayed on.

Great package though and very much appreciated!

**Comment by milewski** [comment]
Hi @CitizenBeta if you could submit a PR updating the README would be awesome, as the creator and my use case sometimes I miss that **other may use this differently from the way I am** so that's the reason why the documentation doesn't reflect that, but glad you figured that out

**Comment by LorenzoSapora** [comment]
@CitizenBeta If you remember what you did, could you elaborate? I'll happily write up a PR for the docs based on your experience.

**Comment by RyanPaiva56** [comment]
@LorenzoSapora 

Yes, all you have to do is the steps in the documentation but do it on the resource that you want to display, not the one that you want it to show up on. The official docs assume you want them both on the same page.

**Comment by arturasfrontit** [comment]
> Hi @CitizenBeta if you could submit a PR updating the README would be awesome, as the creator and my use case sometimes I miss that **other may use this differently from the way I am** so that's the reason why the documentation doesn't reflect that, but glad you figured that out

do you still need it?

**Comment by milewski** [comment]
~Does this package work in nova4? 😃~ oh it does!

Yeah would be helpful to others to have a better description of how to use it / how it can be used etc...
