### ISSUE TITLE
This doesn't seem to work for me... here are some things I've tried.

### ISSUE THREAD

**Issue by MikeCraig418** [dcasia/custom-relationship-field#5]
This works:
```
$query->where('id', '<', 100);
```

❗ This does not:
```
$query = DB::table('users')
            ->where('id', '<', 100);

return $query
```

This works:
```
$query = $query
            ->leftJoin('buyer_buyers_agent AS bba', 'bba.buyer_id', '=', 'users.id')

return $query
```

❗ This does not:
```
$query = $query
            ->leftJoin('buyer_buyers_agent AS bba', 'bba.buyer_id', '=', 'users.id')
            ->where('bba.buyer_id', '<', 100)

return $query
```

I was expecting to customize my query. Can I make any query? What are the limitations?

Thanks!

**Comment by milewski** [comment]
This is a limitation of how laravel nova works itself behind the scene, you are given a $query object you can only modify/add additional constraints to it, but not discard the query given and return a new one

```php
$query = DB::table('users')
            ->where('id', '<', 100);

return $query
```

The returned $query object in this example is not even used at all.


I suggest you to take a look at this method: https://github.com/dcasia/custom-relationship-field/blob/4dc8a20739c1c0bc406b129d584e365844caee7a/src/CustomRelationshipFieldTrait.php#L138-L163 and override if to fit your needs
