### ISSUE TITLE
Trait collision with ConditionalContainer

### ISSUE THREAD

**Issue by cord** [dcasia/custom-relationship-field#7]
Great work!

When using together with `ConditionalContainer` I get following trait collision

`Trait method 'availableFields' will not be applied because it collides with 'HasConditionalContainer'`

Is there a way to solve this?

**Comment by milewski** [comment]
There is no real bullet-proof solution for this yet, laravel nova should do something similar to how eloquent boot traits to be able to stop overriding these methods... but this is an issue that has come up multiple times in other repositories as well.. I think you can follow this workaround it should work:

https://github.com/dcasia/nova-json-wrapper/issues/4#issuecomment-559796743
https://github.com/dcasia/nova-json-wrapper/issues/10#issuecomment-665444790

**Comment by cord** [comment]
wonder if `insteadof` could be used - but which `availableFields` is the one which would support both correctly?

https://www.php.net/manual/en/language.oop5.traits.php

```
    use A, B {
        B::smallTalk insteadof A;
        A::bigTalk insteadof B;
    }
```

**Comment by milewski** [comment]
You need both .. they all call `parent::availableFields()` thats why extending the class works...

**Comment by milewski** [comment]
No longer an issue on the latest version
